# control_plane/repositories/organisation_repository.py
from __future__ import annotations

from typing import Optional, Protocol, Tuple

from control_plane.governance.organisations.organisation import Organisation, OrganisationId
from core.typing import TenantId


class OrganisationRepository(Protocol):
    def get_by_id(self, org_id: OrganisationId) -> Optional[Organisation]: ...
    def get_by_slug(self, slug: str) -> Optional[Organisation]: ...
    def list_for_tenant(self, tenant_id: TenantId) -> Tuple[Organisation, ...]: ...
    def save(self, organisation: Organisation) -> Organisation: ...
    def delete(self, org_id: OrganisationId) -> None: ...
